# Sever
server:
  port: 8080

# Spring  
spring:
  application:
    name: South System
    title: Cooperativism Voting Management 
    version: 1 
  main:
    banner-mode: CONSOLE
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgres://uvgzxkmmzpycvs:3b8108e75c26d687769a18251f3c1aaa2f2401a91fdbf57f7f3a9b6066b992e5@ec2-107-21-67-46.compute-1.amazonaws.com:5432/d7bqapj9iae4f6 
    username: uvgzxkmmzpycvs
    password: 3b8108e75c26d687769a18251f3c1aaa2f2401a91fdbf57f7f3a9b6066b992e5
  jpa:
    ddl-auto: none
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
      
# API's URL's
api:
  member-cpf: 
  upload-service: https://user-info.herokuapp.com/users/


# DOCS
springdoc:
  swagger-ui:
    path: /swagger
    disable-swagger-default-url: false
  pathsToMatch: /**
    
# LOG
logging:
  level:
    org.springframework: ERROR
    br.com.southsystem.cooperativism: DEBUG
  