# Sever
server:
  port: 8080

# Spring  
spring:
  application:
    name: South System
    title: Cooperativism Voting Management 
    version: 1 
  datasource:
    url: ${JDBC_DATASOURCE_URL}
  jpa:
    ddl-auto: none
    show-sql: true
    open-in-view: false
    generate-ddl: true
      
# API's URL's
api:
  member-cpf: 
  upload-service: https://user-info.herokuapp.com/users/


# DOCS
springdoc:
  swagger-ui:
    path: /swagger
    disable-swagger-default-url: false
  pathsToMatch: /**
    
# LOG
logging:
  level:
    org.springframework: ERROR
    br.com.southsystem.cooperativism: DEBUG
  